Closes out Issue #9 - Add a "settings" modal
the-collab-lab/tcl-pilot-2020-05 pull request #23
Opened 2020-06-02 22:57 UTC by mjhughes707

## Description

The purpose of this PR is to implement the on and off toggling of the "settings" modal, as well as the creation of its basic UI. Further additions to the modal will be addressed in a separate issue.

## Actions

- Added a new boolean state (displayModal) to represent the on and off display of the modal
- Created open and close functions for the modal - passed to the header through props, along with the displayModal state
- Added a "gear" icon button to the header + updated styling
- Hooked up the openModal function to the "gear" icon button
- Created a SettingsModal component with corresponding styling - inherits closeModal function
- Utilized a logical && operator to determine whether or not to display the modal, based on the displayModal state 

## Related Issue

Closes #9 

## Acceptance Criteria

- [x]  Add an icon + link to the top/right of the app in the Header (you can use public/img/settings.png for the icon)
- [x] When the user taps the settings icon, a modal should show over the top of the app
- [ ] Along with a modal should appear an icon + link in the same spot as the settings icon that can be used to close the modal (you can use public/img/close-x.png for the icon)
- [x] The modal should have a heading that says “Settings” (we’ll add the rest of the settings UI next week!)

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

### Before

![Screen Shot 2020-06-02 at 1 41 17 PM](https://user-images.githubusercontent.com/38340128/83576435-ab348280-a4e6-11ea-916f-d3b4c65cada7.png)

### After

#### EXAMPLE 1 - WITH SETTINGS ICON ADDED TO HEADER
![Screen Shot 2020-06-02 at 3 37 18 PM](https://user-images.githubusercontent.com/38340128/83576604-f5b5ff00-a4e6-11ea-8912-d42b7959f55e.png)

2020-06-04 02:14 UTC, AshlingH approved these changes
Great Job folks, was Materialize utilized in this??

2020-06-04 02:14 UTC, AshlingH commented on src/App.css
> +
Really nice simple CSS, well done

2020-06-04 02:14 UTC, AshlingH commented on src/components/Header.js
> +  );
excellent, this is how we worked with Modals with the shopping list task very simple and to the point

2020-06-04 03:06 UTC, segdeha requested changes
The code is looking really good and the modal opens and closes as expected. Nice work!

It looks like the branch has conflicts, so you'll need to resolve those. Additionally, on Safari, the gear icon isn't cooperating (see screenshot).

<img width="616" alt="image" src="https://user-images.githubusercontent.com/4306/83710446-9aaf0580-a5d5-11ea-9f30-3b4f1d3b561f.png">

2020-06-04 03:06 UTC, segdeha commented on src/App.css
> +  height: 100%;
Another way to do this that's not sensitive to if you add padding to the element is to specify:

    bottom: 0;
    left: 0;
    right: 0;
    top: 0;

Same effect, but no chance of accidental scroll bars.

2020-06-04 03:06 UTC, segdeha commented on src/App.css
> +
Agreed!

2020-06-04 03:06 UTC, segdeha commented on src/components/Header.js
> +      {displayModal && <SettingsModal setDisplayModal={setDisplayModal} />}
Nice! Both concise and clear. Love it!

2020-06-07 20:39 UTC, segdeha approved these changes
Happy to fix the button placement later, so approving!

Need to fix the merge conflicts, but otherwise good to go 💪

2020-06-07 20:39 UTC, segdeha commented on src/App.css
> +  right: 20px;
Adding `top: 6px;` to this ruleset fixes it when I apply that locally. Might not be an ideal fix, but maybe good enough?

Also, I'm happy to go ahead and approve this and we can fix the button placement later!

2020-06-08 00:22 UTC, merged