Welcome Screen - App Title- to Home
the-collab-lab/tcl-pilot-2020-05 pull request #24
Opened 2020-06-04 01:07 UTC by AshlingH

## Description

When the user taps the title of the App , the app returns to the original screen when the ap first opens.

## Related Issue
close #12 

## Acceptance Criteria

- [ ] User can tap the app title (the name of the app in the Header component) to return the app to showing the original screen that shows in the Footer when the app first opens)

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

### Before

### After

## Testing Steps / QA Criteria

2020-06-04 02:15 UTC, AshlingH commented
hahah Amber caught us in the screenshot for your viewing pleasure!!

2020-06-04 03:10 UTC, mjhcodes requested changes
It appears the code from the previous issue has been carried over into this PR, which makes it a little difficult to address the specific changes. Is there a way to merge that PR into master and then back into this one to help simplify it? Hopefully, that would help. 🤞 

There's also some commented out code, which would be good to clean up first before merging into master, as well as a couple of prop type failures in the console to address.

Lastly, when the title is clicked, it seems to fully reload the app and thus moves the map from the user's location or custom center to the default location. Is this what was intended? I wonder if there's a way to render a change to just the footer itself, perhaps by instead toggling the `displayInformation` state to revert to the `defaultFooter`, which would avoid the map being affected.

2020-06-04 03:10 UTC, mjhcodes commented on src/App.js
> +   }*/
Is this required? If not, it'd likely be best to remove, as commented out code can clutter up the app pretty fast.

2020-06-04 03:10 UTC, mjhcodes commented on .vscode/settings.json
> +        "headerbutton"
This is interesting. What does this do?

2020-06-04 03:10 UTC, mjhcodes commented on src/components/Map.js
> +    : 'map-center';*/
Is this also able to be removed?

2020-06-04 03:10 UTC, mjhcodes commented on src/components/Map.js
> +  handleCenterChanged: PropTypes.func.isRequired,
It appears there's two prop type failures in the console related to these, as it's marked required, but the value is undefined. Worth investigating what's being passed down.

2020-06-04 03:29 UTC, segdeha requested changes
So, this satisfies the AC as they're written, but...I'm going to rewrite the AC 😅 

The problem is that by calling `window.location.reload()` we reload the whole app, which (for example) resets the permissions for having shared one's location and puts the user back in Cork, which, while lovely, may not be what they want 😛 

For future cohorts, I'll be adding an additional condition on the AC which is "without reloading the app"

2020-06-04 03:29 UTC, segdeha commented on src/App.js
> +    window.location.reload(false);
I can understand why you took this approach, but the attached GIF shows the problem with it. Clicking in the title reloads the whole page. If I've already shared my location, I have to do so again. If I'm centered on anywhere other than the default, I'm taken back to the default. 😬 

Another approach that doesn't have that problem would be to use state to manage whether there's a pin location showing. If no location is showing, show the default info. Have the title reset the app to that state. Let me know if you have questions!

![Screen Cast 2020-06-03 at 8 17 24 PM](https://user-images.githubusercontent.com/4306/83711172-5b81b400-a5d7-11ea-8433-dfb52a902225.gif)

2020-06-04 03:29 UTC, segdeha commented on src/App.css
> +.header-btn {
Is it my imagination or is there a bunch of code that _looks_ like it's been changed in this PR, but was changed in a previous one? Maybe merging an up-to-date `master` branch into your branch will get rid of the extra code?

The main problem being that it's hard to tell what were the changes actually related to addressing this issue when there's other code showing up as green, too. Thanks!

2020-06-04 03:29 UTC, segdeha commented on src/App.js
> +  /* const onPositionChanged = (location) => {
Will want you to remove commented out code prior to merging. Thanks!

2020-06-04 03:29 UTC, segdeha commented on src/App.js
> +      // onPositionChanged={onPositionChanged}
Will want you to remove commented out code prior to merging. Thanks!

2020-06-04 03:29 UTC, segdeha commented on src/components/Footer.js
> +    <div>
What's the reason for having a `<div>` nested inside the `<section>`? I can imagine wanting that if you want the content inside the `<div>` to scroll inside the `<section>` container, but that's not currently happening.

2020-06-04 03:29 UTC, segdeha commented on src/components/Map.js
> +  /*const mapCenterClassnames = userHasPanned ?
Will want you to remove commented out code prior to merging. Thanks!

2020-06-04 03:29 UTC, segdeha commented on src/components/Map.js
> +             // handleCenterChanged={handleCenterChanged}
Will want you to remove commented out code prior to merging. Thanks!

2020-06-04 03:29 UTC, segdeha commented on src/lib/isObjEmpty.js
> +  return Object.keys(obj).length === 0;
Clever! Now I want to go back up and see where this is used 😅

2020-06-04 03:29 UTC, segdeha commented on src/components/Map.js
> +     // handleCenterChanged();
Will want you to remove commented out code prior to merging. Thanks!

2020-06-04 03:41 UTC, ajiles91 commented on src/App.js
> +   }*/
No, we had kept this most of this code commented out because we weren't sure if we needed it to resolve the last 2 ACs from map panning issue yet

2020-06-04 03:47 UTC, AshlingH commented
Thanks All, I merged Master and removed redundent code. I had some stashing issues should have probably started a fresh branch! We spoke abou the reload as well from a user perspective and will change it so the home screen goes back to the shared location. Thanks!

2020-06-04 03:49 UTC, AshlingH commented on .vscode/settings.json
> +        "headerbutton"
not sure what you are referring to?

2020-06-12 01:43 UTC, segdeha requested changes
So, clicking the title now restores the default lower pane. But..there are a couple of problems:

1. For some reason I can no longer pan in device mode (though I see that's a problem on the production site as well)
2. Clicking the "center on me" icon causes a console error

![Screen Cast 2020-06-11 at 6 26 33 PM](https://user-images.githubusercontent.com/4306/84455359-0155a400-ac12-11ea-8a15-5e729e20ce23.gif)

2020-06-12 01:43 UTC, segdeha commented on src/App.js
> +  const handleClick = () => {
Can we change the name of this method to something more descriptive/semantic?

2020-06-12 01:43 UTC, segdeha commented on src/components/Header.js
> +      <button className="header-btn" onClick={(handleCenterClick)} to="/">
Curious why the method name needs to be in parentheses?

2020-06-12 01:43 UTC, segdeha commented on src/components/PinDescription.js
> +const PinDescription = ({ title, image, description, }) => {
Let's lose the trailing comma, thanks!

2020-06-15 03:17 UTC, segdeha requested changes
This is all looking and working great, except that when I click on the "center on me" icon, I get an error in the console.

![console error](https://user-images.githubusercontent.com/4306/84614742-e5553b00-ae7b-11ea-8754-4f4f56e2b964.png)

Was this broken prior to your changes? If so, let's file a bug and come back to fix that button. If this PR has somehow broken that button, we need to fix it prior to merging. Thanks!

2020-06-15 03:17 UTC, segdeha commented on src/App.js
> +    function success(pos) {
I'm a fan of this pattern of encapsulating functions that are only used within the scope of the handler inside it like this. Nice work!

2020-06-16 00:55 UTC, merged